### ISSUE TITLE
Captcha errors

### ISSUE THREAD

**Issue by ShazadSkriptREPO** [InstantlyMoist/Captcha#9]
When new player join server nothing happens and console spams error like 

20:18:23 WARN]: [Captcha] Task #3724 for Captcha v1.044 generated an exception
java.lang.NullPointerException: null
	at me.kyllian.captcha.player.PlayerData.cancel(PlayerData.java:112) ~[?:?]
	at me.kyllian.captcha.handlers.CaptchaHandler.removeAssignedCaptcha(CaptchaHandler.java:64) ~[?:?]
	at me.kyllian.captcha.listeners.PlayerChatListener$1.run(PlayerChatListener.java:44) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by InstantlyMoist** [comment]
Try resetting your maps.yml
